### ISSUE TITLE
[Question]  All three ways of running the code failed in Windows

### ISSUE THREAD

**Issue by 623637719** [PKU-Alignment/omnisafe#247]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-Alignment/omnisafe/issues) and [Discussions](https://github.com/PKU-Alignment/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-Alignment/omnisafe/discussions/new).

### Questions

![image](https://github.com/PKU-Alignment/omnisafe/assets/111236370/fe57c2ba-2bac-4bbc-aac4-f12eba54c72a)
**As the documentation shows,there are three ways to run the code**

1.![ca88bd501d03b0045bf97f3a296cd3e](https://github.com/PKU-Alignment/omnisafe/assets/111236370/ed658f80-c6aa-4d44-8bf5-164c6933f313)
2.![725f9a1282b367fc4c3405aafaeca3c](https://github.com/PKU-Alignment/omnisafe/assets/111236370/a6ad34cd-3ab7-455a-ad68-3dfafd3d3895)
3.![51bcb9b069da653f61a5c9289b6f6a4](https://github.com/PKU-Alignment/omnisafe/assets/111236370/64a52f44-2635-40f7-8e0c-bd46ad8be718)
I've tried every way to run the code but it got errors.Help.....

**Comment by Gaiejj** [comment]
We are very sorry for the inconvenience caused to your experience. There may be some misunderstanding here. The first two training methods in the document correspond to ``train_from_yaml.py`` and ``train_from_custom_dict.py`` under the ``omnisafe/examples/`` path. You can fill these two files with content from the documentation and run them. After my local test, the training can be performed normally. As for the third training method, I also found no problems running it locally. Can you provide more detailed error information so that we can solve your problem more quickly？

**Comment by Gaiejj** [comment]
In addition to these three training methods, you can run the following command in the terminal to perform CPO training.
```python
conda activate omnisafe
omnisafe train --algo CPO --env-id SafetyPointGoal1-v0
```
This method also enables algorithm training with the default parameters given in ``omnisafe/configs/on-policy/CPO.yaml``.

**Comment by zmsn-2077** [comment]
Hi, @623637719,
I'm sorry, but the use case in the figure is intended for `Windows`. However, due to multiple dependencies, including the lack of official support for Windows by `Gymnasium`. Thus, OmniSafe doesn't work under `Windows`. We recommend using [WSL](https://learn.microsoft.com/en-us/windows/wsl/install) to run the program under the Ubuntu environment on `Windows`. We have also re-checked our results on Ubuntu, shown in the following steps.
1. Create a test environment via conda.
```bash
conda create -n test_omnisafe python=3.8
```
2. Install OmniSafe from PyPI.
```bash
pip install omnisafe
```
3. Test in ipython.
<img width="1208" alt="image" src="https://github.com/PKU-Alignment/omnisafe/assets/73586554/67075f3e-a4da-4ffb-bd58-e2025bae6767">

In addition to that, we also support running on Mac OS with Apple Silicon, but this requires some additional configuration. More details can be referred to `[BUG] Omnisafe cannot run on a Mac M1 device` #190.

**Comment by zmsn-2077** [comment]
Feel free to ask to reopen this if you have more questions.

**Comment by 623637719** [comment]
感谢回复！咱们中国人给中国人发邮件就不用发英文了，我找到了你的这两个文件，并且尝试运行了他们，我设置的算法选择是CPO，

刚开始运行几次是这样子的，正常，但是运行了一定轮数之后发生了报错

报错信息如下图

我现在在你们北大前沿计算中心的实验室做科研，目前希望能够通过这个地方是去使用safe RL算法去做一些项目，最近还是蛮希望能够解决这个问题的，再一次的，谢谢回复！&nbsp;


峤
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jiayi ***@***.***&gt;; 
发送时间: 2023年6月2日(星期五) 凌晨1:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PKU-Alignment/omnisafe] [Question]  All three ways of running the code failed (Issue #247)





 
We are very sorry for the inconvenience caused to your experience. There may be some misunderstanding here. The first two training methods in the document correspond to train_from_yaml.py and train_from_custom_dict.py under the omnisafe/examples/ path. You can fill these two files with content from the documentation and run them. After my local test, the training can be performed normally. As for the third training method, I also found no problems running it locally. Can you provide more detailed error information so that we can solve your problem more quickly？

**Comment by Gaiejj** [comment]
As soon as I received your message, I immediately began testing. 
First, I installed the latest version of Omnisafe from the main branch on my personal Linux computer and ran the main training program for CPO using the following command. 
```python
cd examples
python train_policy.py --algo CPO
```
Second, I also created a Docker image.
```bash
cd omnisafe
sudo docker build -t omnisafe .
sudo docker -i -t omnisafe
```

Then run the same command
```python
cd examples
python train_policy.py --algo CPO
```

Both testing methods yielded the same result, which is the successful completion of 1e7 steps in CPO's SafetyPointGoal1. 
![image](https://github.com/PKU-Alignment/omnisafe/assets/108712610/82d94e5f-ba45-47f0-9eaa-9f3d5916814e)
I noticed that in your previous questions, you mentioned installing Omnisafe via PyPI, which differs from the latest version of the source code. In my testing, I also tested Omnisafe installed via PyPI and did not encounter any issues. The version of Omnisafe I installed via PyPI is 0.4.0. I noticed that you mentioned providing a screenshot of an error message, but unfortunately, I didn't see it. If you can provide detailed version information, it would be helpful for us to assist you in resolving your issue.

**Comment by 623637719** [comment]
再次感谢你的认真解答！不知道是否方便我们约个腾讯会议，然后我共享一下屏幕，我们通过会议沟通一下看看如何解决，我感觉如果你方便直接查看我电脑的一些信息和运行过程的话，我们能够更快解决这个问题
&nbsp;


峤
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jiayi ***@***.***&gt;; 
发送时间: 2023年6月6日(星期二) 凌晨0:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PKU-Alignment/omnisafe] [Question]  All three ways of running the code failed in Windows (Issue #247)





 
As soon as I received your message, I immediately began testing.
 First, I installed the latest version of Omnisafe from the main branch on my personal Linux computer and ran the main training program for CPO using the following command.
 cd examples python train_policy.py --algo CPO
 
Second, I also created a Docker image.
 cd omnisafe sudo docker build -t omnisafe . sudo docker -i -t omnisafe
 
Then run the same command
 cd examples python train_policy.py --algo CPO
 
Both testing methods yielded the same result, which is the successful completion of 1e7 steps in CPO's SafetyPointGoal1.
 
 I noticed that in your previous questions, you mentioned installing Omnisafe via PyPI, which differs from the latest version of the source code. In my testing, I also tested Omnisafe installed via PyPI and did not encounter any issues. The version of Omnisafe I installed via PyPI is 0.4.0. I noticed that you mentioned providing a screenshot of an error message, but unfortunately, I didn't see it. If you can provide detailed version information, it would be helpful for us to assist you in resolving your issue.

**Comment by XuehaiPan** [comment]
@623637719 We do not officially support Windows. Please use WSL, docker, or a native Linux machine to run our code and examples. Also, please provide the relevant information before asking a question, such as your runtime environment and versions, package versions, hyperparameters, and command line options, etc.

PS: Please learn how to ask a question before asking a question and creating a new issue. There is a good lesson [How do I ask a good question?](https://stackoverflow.com/help/how-to-ask) for this.

> 不知道是否方便我们约个腾讯会议

Emailing open-source maintainers directly (or asking for offline help) instead of opening issues on their projects is a rude thing to do. Someone else may face the exact same issue that you are facing. It's not helpful that we resolve this only for you offline. You can post your information, comments, and thoughts on the GitHub page. The whole community can see and learn from that.

**Comment by 623637719** [comment]
感谢回复和指教，这是我第一次在github上提问，有许多规则也不是很清楚，十分抱歉因为还比较萌新所以有所冒犯，这次提问方式不够好我也会注意的。
再一次地，向你们道歉~

&nbsp;


峤
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xuehai ***@***.***&gt;; 
发送时间: 2023年6月6日(星期二) 下午4:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PKU-Alignment/omnisafe] [Question]  All three ways of running the code failed in Windows (Issue #247)





 
@623637719 We do not officially support Windows. Please use WSL, docker, or a native Linux machine to run our code and examples. Also, please provide the relevant information before asking a question, such as your runtime environment and versions, package versions, hyperparameters, and command line options, etc.
 
PS: Please learn how to ask a question before asking a question and creating a new issue. There is a good lesson How do I ask a good question? for this.
  
不知道是否方便我们约个腾讯会议
  
Emailing open-source maintainers directly (or asking for offline help) instead of opening issues on their projects is a rude thing to do. Someone else may face the exact same issue that you are facing. It's not helpful that we resolve this only for you offline. You can post your information, comments, and thoughts on the GitHub page. The whole community can see and learn from that.

**Comment by zmsn-2077** [comment]
hi, @623637719, we can schedule a meeting to help you resolve this issue. We can communicate via email to determine a mutually convenient time for both parties.
