### ISSUE TITLE
about pip install

### ISSUE THREAD

**Issue by Eureke01** [PKU-Alignment/omnisafe#319]
### Required prerequisites

- [X] I have read the documentation <https://omnisafe.readthedocs.io>.
- [X] I have searched the [Issue Tracker](https://github.com/PKU-Alignment/omnisafe/issues) and [Discussions](https://github.com/PKU-Alignment/omnisafe/discussions) that this hasn't already been reported. (+1 or comment there if it has.)
- [X] Consider asking first in a [Discussion](https://github.com/PKU-Alignment/omnisafe/discussions/new).

### Questions

When using it, I encountered the following problems.

![QQ截图20240412160116](https://github.com/PKU-Alignment/omnisafe/assets/104348087/8462e44e-f28c-4610-b7ec-77a2bacf482c)

I would like to ask for advice on how to install successfully if I am not using a virtual environment.

**Comment by Gaiejj** [comment]
First, we would recommend that you install OmniSafe in a virtual environment. More specifically, **we have tested the installation and essential operation of OmniSafe (with a code test coverage of 97%)** in virtual environments corresponding to **Python versions 3.8, 3.9, and 3.10**. Please check if your Python version is consistent.
Secondly, we regret that we did not find any specific error information in the image you reported. You can upload the complete error information so that we can fully understand your problem.

**Comment by Eureke01** [comment]
Thank you for your reply.I know where the problem lies.
